### ISSUE TITLE
Timeout error when navigating

### ISSUE THREAD

**Issue by etanxing** [shawnLiujianwei/puppeteer-lambda#10]
Hey, I deployed to AWS and successfully got a page title but I got a timeout error when navigating. There is no issue running in a normal node env.
>  Navigation Timeout Exceeded: 30000ms exceeded
```
page.click(SEARCH_SELECTOR); 
await page.waitForNavigation();
```

**Comment by shawnLiujianwei** [comment]
@etanxing  1. is you lambda able to access the site  2. check whether the "SEARCH_SELECTOR" exist
