### ISSUE TITLE
_getBrowser : SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by PunkHaz4rd** [shawnLiujianwei/puppeteer-lambda#11]
I have this issue with a basic example:

> node_modules/puppeteer-lambda/src/index.js:11
> const _getBrowser = async (options) => {
>                                            ^ SyntaxError: Unexpected token (

It happens on the line

	const puppeteerLambda = require("puppeteer-lambda");

**Comment by shawnLiujianwei** [comment]
@PunkHaz4rd  does it due to your node version ?

**Comment by PunkHaz4rd** [comment]
Yes, it was my mistake.
I solved it by setting the node version in serverless.yml:
`
provider:
  name: 'aws'
  runtime: ${opt:runtime, 'nodejs8.10'}
`
