### ISSUE TITLE
Missing default fonts

### ISSUE THREAD

**Issue by teocomi** [shawnLiujianwei/puppeteer-lambda#12]
Hello,
I managed to deploy fine, but default system fonts as times New Roman seem to be missing when opening a local html file.
I'm using "chrome in package" and it was downloaded from: https://raw.githubusercontent.com/shawnLiujianwei/puppeteer-lambda-binary/master/chrome/headless_shell.tar.gz

And put in puppeteer-lambda> chrome> headless_shell.tar.gz

**Comment by shawnLiujianwei** [comment]
@teocomi  have a look   https://github.com/adieuadieu/serverless-chrome/blob/master/docs/chrome.md  , try to build it with your own configuration.
