### ISSUE TITLE
AWS SDK is not needed when publishing to lambda

### ISSUE THREAD

**Issue by serdalis** [shawnLiujianwei/puppeteer-lambda#16]
When trying to use this package for the first time,
I couldn't get the size below 52MB and almost called it a lost cause.

However, apparently AWS Lambda does not require AWS SDK in node modules to run correctly, after deleting the node_modules inside puppeteer-lambda, the zip size was 47MB and everything worked correctly.

A note in the readme to help out other people may be a good idea.

Aside from that, great work, worked first time for me where the other packages failed.

**Comment by whoisjuan** [comment]
@serdalis You can upload the zipped Lambda from S3 and you don't have the 52MB limitation.

**Comment by serdalis** [comment]
Huh, I don't know how I missed that, guess I need to do more reading!

Thanks, this is definitely a non issue then.
