### ISSUE TITLE
Unzipped size limit exceeded when trying to deploy

### ISSUE THREAD

**Issue by titel** [shawnLiujianwei/puppeteer-lambda#3]
Thanks for the great package.

We've manage to get everything prepared for running our script with lambda and things work just fine locally using the lambda-local npm package.

When trying to deploy on lambda we're faced with an "Unzipped size must be smaller than" error.

What's the solution to overcome this limitation?

Thanks!

**Comment by shawnLiujianwei** [comment]
@titel can you tell me use which way to build the package for lambda? Chrome in package or not?  And did you mentioned:

And this project use puppeteer so don't forget to set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true before run npm install or yarn when you prepare the package for lambda.

**Comment by titel** [comment]
The requirement for the PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true flag wasn't obvious from the description. Adding that fixes the issue so this can be closed.

Thanks!

**Comment by shawnLiujianwei** [comment]
sorry about that , i have added NOTE to the README.
