### ISSUE TITLE
Chromium revision is not downloaded

### ISSUE THREAD

**Issue by ratkorle** [shawnLiujianwei/puppeteer-lambda#4]
Hi, I have tried multiple options to run a puppeteer lambda function.
If anyone can help me I will be so greatfull.
this is my package.json
`{
  "name": "scraper-surveilance",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "update": "claudia update --keep --use-s3-bucket claudia-lambda-uploads --set-env-from-json test-environment.json"
  },
  "config": {
    "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD": true
  },
  "keywords": [],
  "author": "Ratko Korlevski",
  "license": "ISC",
  "dependencies": {
    "assert": "^1.4.1",
    "mongodb": "^3.1.6",
    "puppeteer-lambda": "^1.0.12"
  },
  "devDependencies": {
    "claudia": "^5.1.2"
  },
  "optionalDependencies": {
    "aws-sdk": "^2.327.0"
  }
}
`
When i run test on my Lambda function I get this error:
`Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/var/task/node_modules/puppeteer/lib/Launcher.js:112:15)
    at <anonymous>`

**Comment by bertyhell** [comment]
If anyone else runs into this, make sure you have the environment variable in lambda config correctly set:
![image](https://user-images.githubusercontent.com/1710840/46948863-c0de0580-d07f-11e8-93a0-7491eb14abb3.png)
